#!/bin/bash

COMPILE_TARGET_INPUT_FILE=$1

echo "compiling ${COMPILE_TARGET_INPUT_FILE} ..."

COMPILE_TARGET_OUTPUT_FILE=${COMPILE_TARGET_INPUT_FILE//.cpp/}
COMPILE_TARGET_OUTPUT_FILE=${COMPILE_TARGET_OUTPUT_FILE##*\/}

clang++ -O2 -std=c++11 -Werror -o bin/${COMPILE_TARGET_OUTPUT_FILE} ${COMPILE_TARGET_INPUT_FILE}

echo "${COMPILE_TARGET_INPUT_FILE} was compiled"